[env]
NODE_ENV = "development"

[tools]
# https://direnv.net/
direnv = "2.37.1"
# https://gitleaks.io/
gitleaks = "8.29.1"
# https://nodejs.org/
node = "24.11.1"
# https://pre-commit.com/
pre-commit = "4.4.0"
# https://taskfile.dev/
task = "3.38.0"
# https://pnpmp.io
pnpm = "10.23.0"
