[env]
NODE_ENV = "development"

[tools]
# https://direnv.net/
direnv = "2.37.1"
# https://gitleaks.io/
gitleaks = "8.30.0"
# https://nodejs.org/
node = "24.13.1"
# https://pre-commit.com/
pre-commit = "4.5.1"
# https://taskfile.dev/
task = "3.38.0"
# https://pnpmp.io
pnpm = "10.29.3"
